name: Build and Push Docker Images

on:
  push:
    branches:
      - main  
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push client Docker image
        working-directory: ./client
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/client:$GITHUB_SHA .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/client:$GITHUB_SHA

      - name: Build and push server Docker image
        working-directory: ./server
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/server:$GITHUB_SHA .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/server:$GITHUB_SHA
